### PR TITLE
mattdrayer/code-output-linebreak: Add break for better HipChat output

### PR DESCRIPTION
**Pull request by mattdrayer**
@feanil -- in order for HipChat to render "/code" output correctly there needs to be a line break just after the command.

### CODE REVIEW

**Comment by feanil** [comment]
@mattdrayer this doesn't seem necessary: 
screen shot 2016-05-24 at 12 40 19 pm


There was a bug on the hipchat side that was preventing this from working but they pushed out a fix late last week.

**Comment by mattdrayer** [comment]
okay -- maybe I just need to update my HipChat client then -- closing the PR!

**Comment by feanil** [comment]
Don't forget to delete your branches.

**Comment by mattdrayer** [comment]
Still doesn't work for me -- I'm running version 4.0.8 -- not going to spend more time on it, though 😄

**Pull request closed without merging**
